export const dictionaryData = [
    {   text: 'Bitcoin halving',
        meaning: 'The Bitcoin halving is an event on the Bitcoin protocol, in which the block reward issued to miners decreases by half at programmed intervals.',
        author: 'Kristy Moreland',
    },
    {   text: 'P2P VPN',
        meaning: 'A P2P VPN is a type of Virtual Private Network that has servers optimized to work with peer-to-peer networks.',
        author: 'Kristy Moreland',
    },
    {   text: 'ScalaHosting',
        meaning: 'ScalaHosting is a leading managed hosting provider that offers secure, scalable, and affordable cloud VPS solutions for businesses.',
        author: 'MAHEEN KANWAL',
    },
    {   text: 'IT Support',
        meaning: 'IT Support Specialists provide assistance and guidance to the users of technology systems so they can operate with fewer failures and problems.',
        author: 'Siji Roy',
    },
    {   text: 'Managed Services',
        meaning: 'In the world of digitalization, every business needs to invest in technology to achieve its business objectives cost-effectively.',
        author: 'Siji Roy',
    },
    {   text: 'QMSS',
        meaning: 'A quality management system (QMS) gives businesses tools to maintain thorough enterprise doc & manage regulatory compliance efficiently.',
        author: 'Jenna Phipps',
    },
    {   text: 'KPMG',
        meaning: 'KPMG is a professional services firm that helps its clients with a variety of financial, tax, business development, and technology consulting services.',
        author: 'Olivia Chakraborty',
    },
    {   text: 'Burn Up vs Burn Down Charts',
        meaning: 'Burn up and burn down charts are visual representations of progress in the scope of a project. ',
        author: 'Sam Ingalls',
    },
    {   text: 'Hewlett Packard Enterprise',
        meaning: 'Hewlett Packard Enterprise (HPE) is a global, edge-to-cloud PaaS company in the IT, internet, software industry.',
        author: 'Alice Musyoka',
    },
    {   text: 'Change Order',
        meaning: 'The purpose of a change order is to keep everyone involved in a project on the same page about what needs to be done and how much it will cost.',
        author: 'Amanda Scheldt',
    },
    {   text: 'Container Registry',
        meaning: 'Container registry software is designed to store container images while inactive and offers automation features for container management.',
        author: 'Jenna Phipps',
    },
    {   text: 'IT Ticketing',
        meaning: 'The software that enables a single source of interaction between the IT service provider and the end user is the IT ticketing system.',
        author: 'Olivia Chakraborty',
    },
    
]