export const dictionaryData = [
    {   id: 1,
        abbr: 'AFAIK',
        meaning: 'As Far As I Know',
    },
    {   id: 2,
        abbr: 'AFK',
        meaning: 'Away From Keyboard',
    },
    {   id: 3,
        abbr: 'AKA',
        meaning: 'Also Known As',
    },
    {   id: 4,
        abbr: 'AMA',
        meaning: 'Ask Me Anything',
    },
    {   id: 5,
        abbr: 'ASAP',
        meaning: 'As Soon As Possible',
    },
    {   id: 6,
        abbr: 'ASL',
        meaning: 'Age, Sex, Location',
    },
]